# ~/.bashrc
# Bash configuration for interactive non-login shells

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Enable vi mode for command line editing
set -o vi

# History
# Don't put duplicate lines or lines starting with space in history
HISTCONTROL=ignoreboth

# Append to history file, don't overwrite it
shopt -s histappend

# Set history length
HISTSIZE=10000
HISTFILESIZE=20000

# Shell opts
# Check window size after each command and update LINES and COLUMNS if needed
shopt -s checkwinsize

# Enable ** pattern for recursive directory matching
shopt -s globstar 2>/dev/null

# Correct minor spelling errors in cd commands
shopt -s cdspell

# Functions
. ~/.config/bashrc/bash_helperfns

# Prompt
# Checks if `tput` can set colors up, which defines if we have colors available
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support
    PS1_a='\e];\s\a\n'                # Cleanup?
    PS1_b='\e[1m\e[36m$(git_branch)'  # Git
    PS1_c='\e[31m\w'                  # Working Dir
    PS1_d='\e[m\n$ '                  # Prompt (on new line)
    PS1="$PS1_a$PS1_b$PS1_c$PS1_d"
else
    # No color support
    PS1='$\u@\h:\w\$ '
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;$\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# ALIASES

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
elif [ -f ~/.config/bashrc/bash_aliases ]; then
    . ~/.config/bashrc/bash_aliases
fi

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# External configs

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [ -f "$HOME/miniconda3/bin/conda" ]; then
    __conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
            . "$HOME/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="$HOME/miniconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
fi
# <<< conda initialize <<<
