# Recordatorios
# <Prefix>S  -- Renombrar sesion
# <Prefix>c  -- Nuevo panel/window dentro de una sesison
# <Prefix>,  -- Renombra un panel window
# <Prefix>I  -- Instalar plugins
# <Prefix>U  -- Actualizar plugins
# 
# Recargar la config
bind r source-file ~/.tmux.conf \; display "Recargado!"

set -g base-index 1              # Numero en windows inician en 1
setw -g mode-keys vi             # Bindings vi en copy-mode
set -s escape-time 0             # Sin delay despues de esc
set -g detach-on-destroy off     # Cuando una sesion se cierra, permanecer dentro de tmux
set -g renumber-windows on       # Sin gaps cuando se cierra una ventana
set -g mouse off                 # Mouse-mode interfiere con la seleccion dentro del terminal

# Cambio prefix a Ctrl+a
unbind C-b
set-option -g prefix C-a

# Sesiones
bind q confirm-before -p "Matar todas las sesiones? (y/[n])" "kill-session -a" # Mata todas las sesiones menos la actual
bind K confirm-before -p "Matar la sesion actual? (y/[n])" kill-session        # Mata la sesion actual
bind N command-prompt -p "Nueva Sesion:" "new-session -A -s '%%'"              # Crea una nueva sesion
bind S command-prompt 'rename-session %%'

# Window splitting
unbind %
unbind '"'
bind s split-window -v -c '#{pane_current_path}' # Split vertical
bind v split-window -h -c '#{pane_current_path}' # Split horizontal
bind c new-window -c '#{pane_current_path}'

## Ventanas flotantes
bind C-j display-popup -h 15 -w 30 -E "tmux-session-switcher"
bind C-o display-popup -E "tmux-zoxide-window"

## Maximizar
bind -r m resize-pane -Z

# Redimension de paneles
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # Navegar con C-hjkl

# Más configs para dracula-plugins: https://github.com/dracula/tmux/blob/master/docs/CONFIG.md
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cwd git ram-usage"

run '~/.tmux/plugins/tpm/tpm'
